# Generated by Django 4.2.11 on 2024-04-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0004_uploadedfile_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='incident_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(default='New', max_length=20),
        ),
    ]
